service: condominions

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  tags:
    projeto: condominions
  environment:
    DYNAMODB_TABLE: condominions-users
    JWT_SECRET: "seu-secret-temporario-123"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: !GetAtt UsersTable.Arn
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!venv/**'

functions:
  register:
    handler: src/auth/register.handler
    package:
      include:
        - src/auth/register.py
        - src/shared/**
      exclude:
        - '**/__pycache__/**'
        - '**/*.pyc'
        - '**/*.pyo'
    events:
      - http:
          path: /auth/register
          method: post
          cors: true
  
  login:
    handler: src/auth/login.handler
    package:
      include:
        - src/auth/login.py
        - src/shared/**
      exclude:
        - '**/__pycache__/**'
        - '**/*.pyc'
        - '**/*.pyo'
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
          
  forgotPassword:
    handler: src/auth/forgot_password.handler
    package:
      include:
        - src/auth/forgot_password.py
        - src/shared/**
      exclude:
        - '**/__pycache__/**'
        - '**/*.pyc'
        - '**/*.pyo'
    events:
      - http:
          path: /auth/forgot-password
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: projeto
            Value: condominions

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: false
    noDeploy:
      - coverage
      - pytest
    usePoetry: false
    useStaticCache: false
    dockerizePip: false
    zip: true
    slim: true
    strip: false
    nativeModules: false
    pythonBin: python
